
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [1]:
import numpy as np

ar = np.arange(10)[::-1]
print(ar)
ar = np.arange(9, -1, -1)
print(ar)

[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
r = sum(list(np.diag(np.arange(9,-1,-1)).flat))
print(r)


45


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [13]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
X = np.linalg.solve(a,b)
print(X)
res = np.allclose( np.dot(a, X), b)
print(res)



[ 0.46666667  3.84444444 -5.55555556]
True


In [ ]:
Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

In [18]:

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32 )
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
res_cos = []
def cosn(a, b):
    scal = np.dot(a, b)
    amod = np.linalg.norm(a)
    bmod = np.linalg.norm(b)
    return scal /(amod*bmod)

for usr_par in users_stats:
    res_cos.append(cosn(usr_par, next_user_stats))

max_res = np.argwhere(res_cos == np.amax(res_cos))
max_res = (max_res.flatten() + np.full(len(max_res), 1)).tolist()
print("Closest users: " + ", ".join(map(str,max_res)))



Closest users: 8, 9
